export const ADMIN_LOADED = "ADMIN_LOADED";
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
export const WRONG_CREDENTIALS = "WRONG_CREDENTIALS";
export const GET_IMAGES = "GET_IMAGES";
